CREATE TABLE "attack_logs" (
  id SERIAL PRIMARY KEY,
  "sourceCountry" VARCHAR(255) NOT NULL,
  "destinationCountry" VARCHAR(255) NOT NULL,
  "attackTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
